server:
  port: 8080
  #servlet:
    #context-path: /frontend

---
  
spring:
  profiles: default
  
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      static-path-pattern: /resources/**

---
spring:
  profiles: docker
  
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      static-path-pattern: /resources/**

---
spring:
  profiles: test
  
